project:
  type: book
  output-dir: _application/zurich_2024

format:
  pdf:
    documentclass: scrreprt
    # template: application_template.tex
    toc: False
    colorlinks: true
    toc-depth: 2
    bibliography: references.bib
    number-sections: false
    template-partials:
      - before-body.tex
      - _titlepage.tex
      - after-body.tex
    include-in-header:
      - in-header.tex
    output-file: "zurich_24_dehne.pdf"

book:
  title: "Application for Postdoc Position (100%) in the Research Group of Professor Karsten Donnay"
  chapters:
    - index.md
    - applications/zurich_2024/motivation_letter.qmd
    - applications/zurich_2024/reference_contacts.qmd
    - publications.qmd
    - software.qmd
    - research.qmd
    - teaching.qmd


