project:
  type: book
  title: "Application for Postdoc Position (100%) in the Research Group of Professor Karsten Donnay"
  output-dir: _application/zurich_2024
format:
  pdf:
    # template: application_template.tex
    toc: False
    colorlinks: true
    toc-depth: 2
    bibliography: references.bib
    number-sections: false
    pdf-engine: lualatex
    template-partials:
      - before-body.tex

params:
  application_title: "Application for Postdoc Position (100%) in the Research Group of Professor Karsten Donnay"

book:
  title: "zurich_application"
  author: "Julian Dehne"
  chapters:
    - index.qmd
    - cv.qmd

execute:
  enabled: true
  echo: true
  warning: false
  error: false
  r-path: "C:/Program Files/R/R-4.4.0/bin/x64/R"
  python-path: "C:/ProgramData/anaconda3/envs/sem_rep_left-right/bin/python"
  freeze: auto