project:
  type: book
  title: "Application for Postdoc Position (100%) in the Research Group of Professor Karsten Donnay"
  output-dir: _application/zurich_2024
format:
  pdf:
    documentclass: scrreprt
    # template: application_template.tex
    toc: False
    colorlinks: true
    toc-depth: 2
    bibliography: references.bib
    number-sections: false
    template-partials:
      - title.tex
      - before-body.tex
      - after-body.tex

book:
  title: "zurich_application"
  author: "Julian Dehne"
  chapters:
    - index.qmd
    - applications/zurich_2024/motivation_letter.qmd
    - cv_old.qmd
    - publications.qmd
    - research.qmd
    - teaching.qmd
