---
title: "About Me"
---

## Education

After completing a BA in European Studies at the University of Passau, I sought to enhance my background with expertise in Computer Science. The dual subject teacher program in Brandenburg and Berlin uniquely offered a combination of Political Science and Computer Science, which aligned perfectly with my interests. In Potsdam, I later received my PhD in the field of learning technologies.

## Work

Following my PhD, I accepted a PostDoc position at the University of Göttingen in the Computational Social Science field. Here, our team has developed a chatbot that can moderate social media discussions trying to make them more deliberative. Unfortunately, Twitter/Musk crashed the scientific experiment in the middle of its lifespan. After that I have worked as a Research Software Engineer with GESIS, and now I am orchestrating the effort to pilot a master curriculum for Research Software Engineering.

# Hobbies

- Music: if I am in Berlin I play clarinet with my old band called DUrlaub
- Gaming: Chess, Dota, Board Games
- Sports: Ski/Snowboard, Swimming
- Writing: [Outdated Blog](https://uzuzjmd.blogspot.com/), some random unfinished book projects