# Teaching

## Classroom Experience
- **Tutor** for Applied Logic and Didactics of Computer Science, University of Potsdam
- **Teacher** for Computer Science and Political Education: Albert-Einstein-Gymnasium, Berlin
- **Seminars and Lectures**:
    - Researching Together - Software Project (MA level)
    - Algorithms for Group Formation (MA level)
    - Principles of E-Learning, Exercise (BA level)
    - Practical E-Learning Project (MA level)
    - Social Network Analysis – Research Seminar (MA level)

## Supervision Experience
- Master Thesis (2)
- Bachelor Thesis (4)

## Evaluations

In Potsdam and Göttingen, the classes I taught were too small to be included in the general evaluation procedures. Nevertheless, I participated in teacher training during my masters and received outstanding marks. It allowed me to benefit from in-depth pedagogical theories and gain full-time teaching experience at the high school level under constant supervision. This level of training is a rare advantage in the context of a standard academic career.
