# Motivational Letter

My main source of motivation is high intrinsic interest in academia and my strong affinity for teaching  that lead me to train as a high-school teacher in the first place.
My research interests reflect my diverse background in social sciences, education and computer science. But instead of seeing this as a disadvantage in a competitive environment where specialization matters most, I embrace it as my identity that as a scientist, naturally, I am a curious person that sees the world as interconnected and fascinating in its many interlacing fields of study.

## Research Interests and Academic Motivation

 (a) Collaborative Self-Regulated Learning:  During my PhD I developed a software that supported student centered collaborative learning. However, in the absence of the leadership of a teacher, the question of how student behavior can be regulated and objectively evaluated are hard to answer. Learning analytics may help the teaching staff to find and design the right point of intervention. Creating a technological environment that includes enough manifestations of the self- or group-centered learning processes in order to form a decent picture remains one of the major challenges in the field of learning technologies.

(b) Creative Learning: During my time at Humboldt university I authored a paper on the operationalization of creativity for the field of learning technologies. Implementing these concepts in a learning environment would also make it more democratic in the sense that lateral thinking is given the credit it deserves alongside classical factors such as intelligence, logic and memory skills. Technology is uniquely suited to support more complex tasks that can analyze creative learning processes.

(c) Learning Outcomes: For the area of learning outcomes the goal was to create a general purpose generic competence-database. The basic idea was that all kinds of learning technologies share internal persistence of learning outcomes and could be integrated within paradigm of service oriented architectures.

(d) Peer Assessment: Also within my PhD I worked on new ways of peer assessment that included a combination of student and teacher influence. My stint at computational social sciences also gave me the idea to include rational choice experiments common in the political sciences in the area of learning technologies.

A common theme is that past and planned research take place in predominantly uncharted and less known methodological spaces where it is hard to produce large quantities of papers that detail different aspects while maintaining a core methodological access point. However, while this may be a disadvantage during the focused PhD stage or even overwhelming when being the core developer in a postdoc project, I strongly believe that given the chance I could promote these issues from the fringes to a more central position within the communities of learning technologies and higher education. It is also the case that some of these issues have become more prominent lately, so that it should be easy to find suitable partners for collaboration. Here I have good starting points with the members of the projects I have worked for but also beyond.

## Technical Background and AI

Over the past three years, I have dedicated myself to the field of computational social sciences. Although this was a detour from my primary focus on learning technologies, this experience allowed me to gain significant expertise in applied machine learning and natural language processing.

Now, I am eager to apply these skills back to the field of learning analytics, where numerous application areas await. For instance, during my PhD, I worked on the COMPBASE project for three years which deals with creating a persistence for learning outcomes across elearning projects. This project was significantly hindered by the challenge of matching similar learning outcomes—a task that large language models can now handle with ease.

There are many more potential applications for these advanced tools in learning analytics, and I would be thrilled to have the opportunity to return to my original field equipped with these new competencies.

## Networks

I have been a researcher both in the field of educational technologies and in the field of higher education. For the stage in my career I feel well-connected to the respective communities through the GI and the DGHD. For instance, I have been part of the PC for the DELFI the last years, and I graduated from one of the most prominent learning technologies working group.

In terms of academic background and methodological skill I bring an especially broad set of perspectives. To paraphrase one of my mentors: yes, the academic world requires specialization and most permanent positions ask of you to be the best in the field, but it is also true that your academic identity is not the lowest common denominator but the union of the fields (education, computer science and political science) you have graduated and worked in.
\
\
Thank you for your consideration!

```{=latex}
\bigskip
{\fontsize{30}{36}\selectfont\textit{\textcalligra{Julian Dehne}}}
```

