# References

- [Valentin Gold](https://valentingold.de/) was substitute Professor for Quantitative Methods in Social Sciences in Göttingen: Valentin lead the Delab project, where I worked for three years building a human-in-the-loop pipeline for interactive social media studies and deliberation research. Valentin's research in computational social science is organized around three larger themes: empirical and computational methodology, deliberative communication, and transfer services.
- [Ulrike Lucke](https://www.uni-potsdam.de/de/multimedia/team/profdr-inghabilulrikelucke/) holds a chair for Complex Multimedia Application Architectures at the University Potsdam. She supervised my PhD thesis and was my boss for over eight years. Her research focuses on the areas of "Mobile and Pervasive Computing," "Interoperability in Heterogeneous Environments," and "E-Learning."
- [Marius Sältzer](https://msaeltzer.com/) is Professor in Oldenburg for Digital Society: Sältzer studied economics and political science in Mannheim and Hamburg. His doctoral thesis, which he completed in 2021 at the University of Mannheim, dealt with methods for capturing the positions of politicians based on their contributions in social media. As a postdoctoral researcher, he first moved to the University of Basel (Switzerland) and then to the Department of Computational Social Science at the Leibniz Institute. Marius and I worked together on two research proposals and mentored me when entering the CSS field.